services:
  backend:
    build: .
    working_dir: /myapp
    container_name: backend_container
    depends_on:
      - db
    ports:
      - '5000:5000'

  db:
    container_name: mongo_db
    image: mongo
    ports: 
      - '27017:27017'
    volumes: 
      - mongo_db:/data/db

volumes:
  mongo_db: